/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.principal;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */

/////////////////// NETBEANS IDE 17
////////////////// GUSTAVO HENRIQUE SEVERIANO

public class ItensCarrinho extends javax.swing.JFrame {

      private static ItensCarrinho unicTableCarrinho;
      private Carrinho unicCar = Carrinho.getCarrinho();
      private int aux = 0;
      

        
    private ItensCarrinho() {
        initComponents();
    }

    ////////////////////////SINGLETON
    public static ItensCarrinho getItensCarrinhoTabela(){
        if(unicTableCarrinho == null){
            unicTableCarrinho = new ItensCarrinho();
        }
        
        return unicTableCarrinho;
    }
    
    public void cadRoupa(){
        //Roupa RP = new Roupa();
    }
    
    public void abreItensCarrinho(){
        ItensCarrinho.getItensCarrinhoTabela().setVisible(true);
    }
    
    
    
    public void adicionarItem(Roupa roupa){
        DefaultTableModel modelo = (DefaultTableModel)JTableCarrinho.getModel();
        
        
        modelo.setRowCount(aux);
        modelo.insertRow(aux, new Object[]{roupa.getNome(), roupa.getCor(), roupa.getTamanho(), roupa.getMarca()});
        
        aux++;
        //Carrinho carUnic = Carrinho.getCarrinho();
       //carUnic.adicionarRoupa(roupa);
      
    }
    
    public void limparTabela() {
            DefaultTableModel modelo = (DefaultTableModel) JTableCarrinho.getModel();
            modelo.setRowCount(0); // Remove todas as linhas da tabela
            aux = 0; // Reinicia o contador auxiliar
}

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableCarrinho = new javax.swing.JTable();
        JBTvoltarMenuCompras = new javax.swing.JButton();
        JBTexcluirDoCarrinho = new javax.swing.JButton();
        JTFfiltro = new javax.swing.JTextField();
        JBTfiltro = new javax.swing.JButton();
        JLBsdleks = new javax.swing.JLabel();
        JLBmeuCarrinho = new javax.swing.JLabel();
        JTFvalorTotalCarrinho = new javax.swing.JTextField();
        JBTvalorTotalCarrinho = new javax.swing.JButton();
        JBTfinalizarCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTableCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Cor", "Tamanho", "Marca"
            }
        ));
        jScrollPane1.setViewportView(JTableCarrinho);

        JBTvoltarMenuCompras.setText("Voltar");
        JBTvoltarMenuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTvoltarMenuComprasActionPerformed(evt);
            }
        });

        JBTexcluirDoCarrinho.setText("Excluir item");
        JBTexcluirDoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTexcluirDoCarrinhoActionPerformed(evt);
            }
        });

        JTFfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFfiltroActionPerformed(evt);
            }
        });

        JBTfiltro.setText("Filtrar:");
        JBTfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTfiltroActionPerformed(evt);
            }
        });

        JLBsdleks.setText("SDLEKS STORE");

        JLBmeuCarrinho.setText("Meu Carrinho:");

        JTFvalorTotalCarrinho.setEditable(false);
        JTFvalorTotalCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFvalorTotalCarrinhoActionPerformed(evt);
            }
        });

        JBTvalorTotalCarrinho.setText("Atualizar Valor");
        JBTvalorTotalCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTvalorTotalCarrinhoActionPerformed(evt);
            }
        });

        JBTfinalizarCompra.setText("Finalizar Compra");
        JBTfinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTfinalizarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBTexcluirDoCarrinho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JBTfiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBTvalorTotalCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JTFvalorTotalCarrinho)
                                    .addComponent(JTFfiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JBTvoltarMenuCompras)
                                    .addComponent(JBTfinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLBmeuCarrinho)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(JLBsdleks)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLBsdleks)
                .addGap(9, 9, 9)
                .addComponent(JLBmeuCarrinho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTexcluirDoCarrinho)
                    .addComponent(JTFfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTfiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFvalorTotalCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTvalorTotalCarrinho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(JBTvoltarMenuCompras)
                .addGap(18, 18, 18)
                .addComponent(JBTfinalizarCompra)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTvoltarMenuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTvoltarMenuComprasActionPerformed
        dispose();
    }//GEN-LAST:event_JBTvoltarMenuComprasActionPerformed

    private void JBTexcluirDoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTexcluirDoCarrinhoActionPerformed
     String auxString;
        
    if (JTableCarrinho.getSelectedRow() != -1) { 
        aux = JOptionPane.showConfirmDialog(null, "Deseja Realmente Excluir o produto?", "Excluir Produto", JOptionPane.YES_NO_OPTION);
        if (aux == 0) {
                       
            DefaultTableModel modelo = (DefaultTableModel) JTableCarrinho.getModel();
            auxString = (String) modelo.getValueAt(JTableCarrinho.getSelectedRow(), 0);   // para referenciar minha coluna nao coloco seu nome, e sim seu numero
            modelo.removeRow(JTableCarrinho.getSelectedRow()); //ps: O (String) em frente a linha serve para converter meu Objeto recebido para String.
                        
            
            for(Roupa roupa : unicCar){
                if (roupa.getNome().equals(auxString)) {
                    unicCar.removerRoupa(roupa);
                    break; // removendo roupa do meu banco
                }
            }
            
             if (auxString.equals("Camiseta")) {
                Camiseta CT = new Camiseta("a", "b", "c", "d", 100);
                CT.aumentarCamisetaDisponivel();
                
            } else if (auxString.equals("Calca")) {
                Calca CL = new Calca("a", "b", "c", "d", 80);
                CL.aumentarCalcaDisponivel();
                
            } else if (auxString.equals("Meia")) {
               Meia ME = new Meia("a", "b", "c", "d", 20);
               ME.aumentarMeiaDisponivel();
            }
            
            
        }            
    }else {
        JOptionPane.showMessageDialog(null, "Selecione um produto para excluir");
    }   
       
    }//GEN-LAST:event_JBTexcluirDoCarrinhoActionPerformed

    
    
    ////////////////////////// FILTRO COMO FUNCIONALIDADE DE RELATORIO
    private void filtrarTabela() {
    // Obter o texto do campo de filtro
    String textoFiltro = JTFfiltro.getText();

    // Criar um filtro de expressão regular para todas as colunas
    RowFilter<DefaultTableModel, Object> filtro = RowFilter.regexFilter("(?i)" + textoFiltro);

    // Obter o modelo da tabela
    DefaultTableModel modelo = (DefaultTableModel) JTableCarrinho.getModel();

    // Criar um classificador de linhas para o modelo da tabela
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);

    // Configurar o filtro para todas as colunas
    sorter.setRowFilter(filtro);

    // Configurar o classificador de linhas na tabela
    JTableCarrinho.setRowSorter(sorter);
}

    
      
 
    private void JTFfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFfiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFfiltroActionPerformed

    private void JBTfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTfiltroActionPerformed
       filtrarTabela();
    }//GEN-LAST:event_JBTfiltroActionPerformed

    private void JBTvalorTotalCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTvalorTotalCarrinhoActionPerformed
        String auxString;
        
        auxString = String.valueOf(unicCar.calcularValor());
        
        this.JTFvalorTotalCarrinho.setText(auxString + " RS");
        
        unicCar.listarRoupas();
        
        
    }//GEN-LAST:event_JBTvalorTotalCarrinhoActionPerformed

    private void JTFvalorTotalCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFvalorTotalCarrinhoActionPerformed
        
    }//GEN-LAST:event_JTFvalorTotalCarrinhoActionPerformed

    private void JBTfinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTfinalizarCompraActionPerformed
        // TODO add your handling code here:
        if(unicCar.getItensCarrinho().isEmpty()){            
            JOptionPane.showMessageDialog(null,"SEU CARRINHO DEVE CONTER AO MENOS 1 ITEM!","Carrinho Vazio",JOptionPane.WARNING_MESSAGE);
            dispose();
        }else{
            MenuDadosCliente.getMenuDadosCliente().setVisible(true);
        }    
    }//GEN-LAST:event_JBTfinalizarCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItensCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItensCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItensCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItensCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ItensCarrinho().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTexcluirDoCarrinho;
    private javax.swing.JButton JBTfiltro;
    private javax.swing.JButton JBTfinalizarCompra;
    private javax.swing.JButton JBTvalorTotalCarrinho;
    private javax.swing.JButton JBTvoltarMenuCompras;
    private javax.swing.JLabel JLBmeuCarrinho;
    private javax.swing.JLabel JLBsdleks;
    private javax.swing.JTextField JTFfiltro;
    private javax.swing.JTextField JTFvalorTotalCarrinho;
    private javax.swing.JTable JTableCarrinho;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
