/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.principal;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
/////////////////// NETBEANS IDE 17
////////////////// GUSTAVO HENRIQUE SEVERIANO


public class MenuCompras extends javax.swing.JFrame {

    /**
     * Creates new form MenuCompras
     */
    private static MenuCompras unicoMenuCompras;
    private Carrinho unicCar = Carrinho.getCarrinho();
    
    
    private MenuCompras() {
        initComponents();
    }
    
    ////////////// SINGLETON
    public static MenuCompras getMenuCompras(){
            if(unicoMenuCompras == null){
                unicoMenuCompras = new MenuCompras();
            }   
            
            return unicoMenuCompras;
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBnomePagina = new javax.swing.JLabel();
        JLBopcoesDeCompra = new javax.swing.JLabel();
        JBTcomprarCamiseta = new javax.swing.JButton();
        JBTcomprarCalca = new javax.swing.JButton();
        JBTcomprarMeia = new javax.swing.JButton();
        JBTvoltarMenuPrincipal = new javax.swing.JButton();
        JLBitem = new javax.swing.JLabel();
        JTFtipo = new javax.swing.JTextField();
        JLBtipo = new javax.swing.JLabel();
        JLBcor = new javax.swing.JLabel();
        JBTcorPreto = new javax.swing.JButton();
        JBTcorBranco = new javax.swing.JButton();
        JBTcorVerdeMilitar = new javax.swing.JButton();
        JLBtamanho = new javax.swing.JLabel();
        JBTsizeP = new javax.swing.JButton();
        JBTsizeM = new javax.swing.JButton();
        JBTsizeG = new javax.swing.JButton();
        JBTsizeGG = new javax.swing.JButton();
        JLBcorItem = new javax.swing.JLabel();
        JTFcorItem = new javax.swing.JTextField();
        JLBtamanho1 = new javax.swing.JLabel();
        JTFtamanhoItem = new javax.swing.JTextField();
        JLBmarca = new javax.swing.JLabel();
        JBTmarca = new javax.swing.JButton();
        JLBmarcaItem = new javax.swing.JLabel();
        JTFmarcaItem = new javax.swing.JTextField();
        JBTadicionarAoCarrinho = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuMeuCarrinho = new javax.swing.JMenu();
        JMenuVerItensCarrinho = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLBnomePagina.setText("SDLEKS STORE");

        JLBopcoesDeCompra.setText("Opcoes de compra:");

        JBTcomprarCamiseta.setText("Comprar Camiseta");
        JBTcomprarCamiseta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcomprarCamisetaActionPerformed(evt);
            }
        });

        JBTcomprarCalca.setText("Comprar Calca");
        JBTcomprarCalca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcomprarCalcaActionPerformed(evt);
            }
        });

        JBTcomprarMeia.setText("Comprar meia");
        JBTcomprarMeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcomprarMeiaActionPerformed(evt);
            }
        });

        JBTvoltarMenuPrincipal.setText("VOLTAR AO MENU PRINCIPAL");
        JBTvoltarMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBTvoltarMenuPrincipalMouseClicked(evt);
            }
        });
        JBTvoltarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTvoltarMenuPrincipalActionPerformed(evt);
            }
        });

        JLBitem.setText("Item:");

        JTFtipo.setEditable(false);
        JTFtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFtipoActionPerformed(evt);
            }
        });

        JLBtipo.setText("Tipo:");

        JLBcor.setText("Cor:");

        JBTcorPreto.setText("Preto");
        JBTcorPreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcorPretoActionPerformed(evt);
            }
        });

        JBTcorBranco.setText("Branco");
        JBTcorBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcorBrancoActionPerformed(evt);
            }
        });

        JBTcorVerdeMilitar.setText("Verde-Militar");
        JBTcorVerdeMilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcorVerdeMilitarActionPerformed(evt);
            }
        });

        JLBtamanho.setText("Tamanho:");

        JBTsizeP.setText("P");
        JBTsizeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTsizePActionPerformed(evt);
            }
        });

        JBTsizeM.setText("M");
        JBTsizeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTsizeMActionPerformed(evt);
            }
        });

        JBTsizeG.setText("G");
        JBTsizeG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTsizeGActionPerformed(evt);
            }
        });

        JBTsizeGG.setText("GG");
        JBTsizeGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTsizeGGActionPerformed(evt);
            }
        });

        JLBcorItem.setText("Cor:");

        JTFcorItem.setEditable(false);
        JTFcorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcorItemActionPerformed(evt);
            }
        });

        JLBtamanho1.setText("Tamanho:");

        JTFtamanhoItem.setEditable(false);
        JTFtamanhoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFtamanhoItemActionPerformed(evt);
            }
        });

        JLBmarca.setText("Marca:");

        JBTmarca.setText("SDLEKS");
        JBTmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTmarcaActionPerformed(evt);
            }
        });

        JLBmarcaItem.setText("Marca:");

        JTFmarcaItem.setEditable(false);
        JTFmarcaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFmarcaItemActionPerformed(evt);
            }
        });

        JBTadicionarAoCarrinho.setText("Adicionar ao Carrinho");
        JBTadicionarAoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTadicionarAoCarrinhoActionPerformed(evt);
            }
        });

        JMenuMeuCarrinho.setText("Opcoes");

        JMenuVerItensCarrinho.setText("Meu carrinho");

        jMenuItem1.setText("Ver Itens");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMenuVerItensCarrinho.add(jMenuItem1);

        JMenuMeuCarrinho.add(JMenuVerItensCarrinho);

        jMenuBar1.add(JMenuMeuCarrinho);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(JLBnomePagina))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBTsizeP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBTsizeM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBTsizeG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBTsizeGG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JBTmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBTcomprarCamiseta)
                                .addGap(18, 18, 18)
                                .addComponent(JBTcomprarCalca, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBTcorPreto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBTcorBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(JBTcomprarMeia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(JBTcorVerdeMilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTFcorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTFtamanhoItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLBcor)
                            .addComponent(JLBtamanho)
                            .addComponent(JLBopcoesDeCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLBitem)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBTvoltarMenuPrincipal)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLBmarca)
                                .addGap(585, 585, 585)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JBTadicionarAoCarrinho)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(JLBtamanho1)
                                            .addComponent(JLBmarcaItem)
                                            .addComponent(JLBcorItem)
                                            .addComponent(JLBtipo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JTFmarcaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBnomePagina)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLBopcoesDeCompra)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBTcomprarCamiseta)
                            .addComponent(JBTcomprarCalca)
                            .addComponent(JBTcomprarMeia))
                        .addGap(24, 24, 24)
                        .addComponent(JLBcor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBTcorPreto)
                            .addComponent(JBTcorBranco)
                            .addComponent(JBTcorVerdeMilitar))
                        .addGap(18, 18, 18)
                        .addComponent(JLBtamanho)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLBitem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBtipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFcorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBcorItem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFtamanhoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBtamanho1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLBmarcaItem)
                            .addComponent(JTFmarcaItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTsizeP)
                    .addComponent(JBTsizeM)
                    .addComponent(JBTsizeG)
                    .addComponent(JBTsizeGG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLBmarca)
                    .addComponent(JBTadicionarAoCarrinho))
                .addGap(18, 18, 18)
                .addComponent(JBTmarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(JBTvoltarMenuPrincipal)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTvoltarMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBTvoltarMenuPrincipalMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JBTvoltarMenuPrincipalMouseClicked

    private void JTFtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFtipoActionPerformed

    private void JBTsizeGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTsizeGGActionPerformed
        JTFtamanhoItem.setText("GG");
    }//GEN-LAST:event_JBTsizeGGActionPerformed

    private void JTFcorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcorItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFcorItemActionPerformed

    private void JBTsizeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTsizeMActionPerformed
        JTFtamanhoItem.setText("M");
    }//GEN-LAST:event_JBTsizeMActionPerformed

    private void JTFtamanhoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFtamanhoItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFtamanhoItemActionPerformed

    private void JTFmarcaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFmarcaItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFmarcaItemActionPerformed

    private void JBTvoltarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTvoltarMenuPrincipalActionPerformed
        int aux = JOptionPane.showConfirmDialog(null, "Deseja voltar ao Menu Principal?", "Voltar ao Menu Principal", JOptionPane.YES_NO_OPTION);
            if(aux == 0){
                dispose();
            }
    }//GEN-LAST:event_JBTvoltarMenuPrincipalActionPerformed

    private void JBTcomprarCamisetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcomprarCamisetaActionPerformed
       JTFtipo.setText("Camiseta");
    }//GEN-LAST:event_JBTcomprarCamisetaActionPerformed

    private void JBTcomprarCalcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcomprarCalcaActionPerformed
        JTFtipo.setText("Calca");
    }//GEN-LAST:event_JBTcomprarCalcaActionPerformed

    private void JBTcomprarMeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcomprarMeiaActionPerformed
        JTFtipo.setText("Meia");
    }//GEN-LAST:event_JBTcomprarMeiaActionPerformed

    private void JBTcorPretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcorPretoActionPerformed
        JTFcorItem.setText("Preto");
    }//GEN-LAST:event_JBTcorPretoActionPerformed

    private void JBTcorBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcorBrancoActionPerformed
        JTFcorItem.setText("Branco");
    }//GEN-LAST:event_JBTcorBrancoActionPerformed

    private void JBTcorVerdeMilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcorVerdeMilitarActionPerformed
        JTFcorItem.setText("Verde-Militar");
    }//GEN-LAST:event_JBTcorVerdeMilitarActionPerformed

    private void JBTsizePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTsizePActionPerformed
        JTFtamanhoItem.setText("P");
    }//GEN-LAST:event_JBTsizePActionPerformed

    private void JBTsizeGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTsizeGActionPerformed
        JTFtamanhoItem.setText("G");
    }//GEN-LAST:event_JBTsizeGActionPerformed

    private void JBTmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTmarcaActionPerformed
        JTFmarcaItem.setText("SDLEKS");
    }//GEN-LAST:event_JBTmarcaActionPerformed

    
    private void JBTadicionarAoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTadicionarAoCarrinhoActionPerformed
      int aux = JOptionPane.showConfirmDialog(null, "Deseja adicionar o item ao seu carrinho?", "Adicionar item ao carrinho", JOptionPane.YES_NO_OPTION);
      String auxString = JTFtipo.getText();
      Boolean auxBoolean;
      
    if (aux == 0) {  
        
        switch(auxString){
////////////////////////////////////////////////////////////////////////////////////////////////////////////////            
          case "Camiseta":
            
            Camiseta CT = new Camiseta("", "", "", "", 100);
            auxBoolean = CT.verificarQTDcamisetas();
            
            
               /* if(auxBoolean == false){
                    JOptionPane.showMessageDialog(null, "DESCULPE, SEM MAIS ITENS DESTE TIPO NO ESTOQUE!");
                    break;
                }else{
                    CT.diminuirCamisetaDisponivel();
                    JOptionPane.showMessageDialog(null, "AINDA RESTAM: " + CT.getQtdCamisetasDisponivel() + " EM ESTOQUE!");
                } */
            
                        CT.setNome(JTFtipo.getText());
                        CT.setCor(JTFcorItem.getText());
                        CT.setTamanho(JTFtamanhoItem.getText());
                        CT.setMarca(JTFmarcaItem.getText());
                        CT.setValor(100);
                      
                if (!CT.getNome().isEmpty() && !CT.getCor().isEmpty() && !CT.getTamanho().isEmpty() && !CT.getMarca().isEmpty()) {
                    
                    //ItensCarrinho.getItensCarrinhoTabela().adicionarItem(CT);
                    //unicCar.adicionarRoupa(CT);
                    
                        if(auxBoolean == false){
                                JOptionPane.showMessageDialog(null, "DESCULPE, SEM MAIS ITENS DESTE TIPO NO ESTOQUE!");
                        break;
                        }else{
                            CT.diminuirCamisetaDisponivel();
                            ItensCarrinho.getItensCarrinhoTabela().adicionarItem(CT);
                            unicCar.adicionarRoupa(CT);                            
                            JOptionPane.showMessageDialog(null, "AINDA RESTAM: " + CT.getQtdCamisetasDisponivel() + " EM ESTOQUE!");
                                                       
                        }
                             
                    JOptionPane.showMessageDialog(
                        null, "Camiseta adicionada com Sucesso!", "Inserção de Roupa", JOptionPane.INFORMATION_MESSAGE);
                    
                            JTFtipo.setText("");
                            JTFcorItem.setText("");
                            JTFtamanhoItem.setText("");
                            JTFmarcaItem.setText("");
                    
                }else {
                        JOptionPane.showMessageDialog(
                        null, "Por favor, preencha todos os campos da roupa.", "Inserção de Roupa", JOptionPane.WARNING_MESSAGE);
                }
           break;
/////////////////////////////////////////////////////////////////////////////////////           
          case "Calca":
              
            Calca CL = new Calca("", "", "", "", 80);
            auxBoolean = CL.verificarQTDcalca();
            
    
                        CL.setNome(JTFtipo.getText());
                        CL.setCor(JTFcorItem.getText());
                        CL.setTamanho(JTFtamanhoItem.getText());
                        CL.setMarca(JTFmarcaItem.getText());
                        CL.setValor(80);
                
       
                if (!CL.getNome().isEmpty() && !CL.getCor().isEmpty() && !CL.getTamanho().isEmpty() && !CL.getMarca().isEmpty()) {
                                       
                    if(auxBoolean == false){
                        JOptionPane.showMessageDialog(null, "DESCULPE, SEM MAIS ITENS DESTE TIPO NO ESTOQUE!");
                        break;
                    }else{
                        CL.diminuirCalcaDisponivel();
                        ItensCarrinho.getItensCarrinhoTabela().adicionarItem(CL);
                        unicCar.adicionarRoupa(CL);
                        JOptionPane.showMessageDialog(null, "AINDA RESTAM: " + CL.getQtdCalcaDisponivel() + " EM ESTOQUE!");
                    }
                    
               
                    JOptionPane.showMessageDialog(
                        null, "Calca adicionada com Sucesso!", "Inserção de Roupa", JOptionPane.INFORMATION_MESSAGE);
                    
                            JTFtipo.setText("");
                            JTFcorItem.setText("");
                            JTFtamanhoItem.setText("");
                            JTFmarcaItem.setText("");
                    
                }else {
                        JOptionPane.showMessageDialog(
                        null, "Por favor, preencha todos os campos da roupa.", "Inserção de Roupa", JOptionPane.WARNING_MESSAGE);
                }
           break;     
 ////////////////////////////////////////////////////////////////////////////////////////////////////////////                          
          case "Meia":
              
                        Meia ME = new Meia("", "", "", "", 20);
                        auxBoolean = ME.verificarQTDmeia();
            
                  
                    
                        ME.setNome(JTFtipo.getText());
                        ME.setCor(JTFcorItem.getText());
                        ME.setTamanho(JTFtamanhoItem.getText());
                        ME.setMarca(JTFmarcaItem.getText());
                        ME.setValor(20);
                        
                
       
                if (!ME.getNome().isEmpty() && !ME.getCor().isEmpty() && !ME.getTamanho().isEmpty() && !ME.getMarca().isEmpty()) {
                     
                    if(auxBoolean == false){
                            JOptionPane.showMessageDialog(null, "DESCULPE, SEM MAIS ITENS DESTE TIPO NO ESTOQUE!");
                            break;
                    }else{
                            ME.diminuirMeiaDisponivel();
                            ItensCarrinho.getItensCarrinhoTabela().adicionarItem(ME);
                            unicCar.adicionarRoupa(ME);                           
                            JOptionPane.showMessageDialog(null, "AINDA RESTAM: " + ME.getQtdMeiaDisponivel()+ " EM ESTOQUE!");
                    }
                    
                    
                    
                    JOptionPane.showMessageDialog(
                        null, "Par de meia adicionado com Sucesso!", "Inserção de Roupa", JOptionPane.INFORMATION_MESSAGE);
                    
                            JTFtipo.setText("");
                            JTFcorItem.setText("");
                            JTFtamanhoItem.setText("");
                            JTFmarcaItem.setText("");
                    
                }else {
                        JOptionPane.showMessageDialog(
                        null, "Por favor, preencha todos os campos da roupa.", "Inserção de Roupa", JOptionPane.WARNING_MESSAGE);
                }
                 
          break;    
          
          default:
              JOptionPane.showMessageDialog(null,"DEVE SELECIONAR AO MENOS 1 TIPO DE ITEM","ITEM NAO SELECIONADO",JOptionPane.ERROR_MESSAGE);
              
          break;    
          
          
          
        }        
                
    }else {
       
        dispose();
    }            
                   
    }//GEN-LAST:event_JBTadicionarAoCarrinhoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ItensCarrinho.getItensCarrinhoTabela().abreItensCarrinho();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
   
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTadicionarAoCarrinho;
    private javax.swing.JButton JBTcomprarCalca;
    private javax.swing.JButton JBTcomprarCamiseta;
    private javax.swing.JButton JBTcomprarMeia;
    private javax.swing.JButton JBTcorBranco;
    private javax.swing.JButton JBTcorPreto;
    private javax.swing.JButton JBTcorVerdeMilitar;
    private javax.swing.JButton JBTmarca;
    private javax.swing.JButton JBTsizeG;
    private javax.swing.JButton JBTsizeGG;
    private javax.swing.JButton JBTsizeM;
    private javax.swing.JButton JBTsizeP;
    private javax.swing.JButton JBTvoltarMenuPrincipal;
    private javax.swing.JLabel JLBcor;
    private javax.swing.JLabel JLBcorItem;
    private javax.swing.JLabel JLBitem;
    private javax.swing.JLabel JLBmarca;
    private javax.swing.JLabel JLBmarcaItem;
    private javax.swing.JLabel JLBnomePagina;
    private javax.swing.JLabel JLBopcoesDeCompra;
    private javax.swing.JLabel JLBtamanho;
    private javax.swing.JLabel JLBtamanho1;
    private javax.swing.JLabel JLBtipo;
    private javax.swing.JMenu JMenuMeuCarrinho;
    private javax.swing.JMenu JMenuVerItensCarrinho;
    private javax.swing.JTextField JTFcorItem;
    private javax.swing.JTextField JTFmarcaItem;
    private javax.swing.JTextField JTFtamanhoItem;
    private javax.swing.JTextField JTFtipo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
